name: Build

# on:
#   schedule:
#     - cron: '0 * * * *'

on: push
permissions:
  contents: write

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Generate report
        run: python generate_report.py

      - name: Build site
        run: python build_site.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build
          single-commit: true